name: WakaTime status update

on:
  workflow_dispatch:  
  schedule:
    - cron: '1 0 * * *'  
  push:
    branches: [main]  

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update 🚀"
          STATS_RANGE: "last_7_days"
